version: '3'
services:
  care-central-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - back-network
  db:
      image: postgres:alpine
      container_name: care-central-db
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
      ports:
        - "5432:5432"
      networks:
        - back-network
networks:
  back-network: